### ISSUE TITLE
cmake build failing for NRF targets

### ISSUE THREAD

**Issue by sterlinghughes** [apache/mynewt-newt#159]
newt target show nrf52dk_defapp
targets/nrf52dk_defapp
   app=apps/defapp
   bsp=@apache-mynewt-core/hw/bsp/nrf52dk
   build_profile=optimized

i do:
newt target cmake nrf52dk_defapp

Then make, and I get the following errors: 

Scanning dependencies of target hw_mcu_nordic
[ 75%] Building C object CMakeFiles/hw_mcu_nordic.dir/repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/drivers/src/prs/nrfx_prs.c.obj
[ 75%] Building C object CMakeFiles/hw_mcu_nordic.dir/repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/drivers/src/nrfx_adc.c.obj
[ 76%] Building C object CMakeFiles/hw_mcu_nordic.dir/repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/drivers/src/nrfx_clock.c.obj
[ 76%] Building C object CMakeFiles/hw_mcu_nordic.dir/repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/drivers/src/nrfx_comp.c.obj
[ 77%] Building C object CMakeFiles/hw_mcu_nordic.dir/repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/drivers/src/nrfx_gpiote.c.obj
[ 77%] Building C object CMakeFiles/hw_mcu_nordic.dir/repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/drivers/src/nrfx_i2s.c.obj
[ 78%] Building C object CMakeFiles/hw_mcu_nordic.dir/repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/drivers/src/nrfx_lpcomp.c.obj
[ 78%] Building C object CMakeFiles/hw_mcu_nordic.dir/repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/drivers/src/nrfx_pdm.c.obj
[ 79%] Building C object CMakeFiles/hw_mcu_nordic.dir/repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/drivers/src/nrfx_power.c.obj
[ 79%] Building C object CMakeFiles/hw_mcu_nordic.dir/repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/drivers/src/nrfx_power_clock.c.obj
In file included from /Users/sterling/dev/mynewt/defproj/repos/apache-mynewt-core/hw/mcu/nordic/include/nrfx_glue.h:35:0,
                 from /Users/sterling/dev/mynewt/defproj/repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/nrfx.h:37,
                 from /Users/sterling/dev/mynewt/defproj/repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/drivers/src/nrfx_power_clock.c:32:
/Users/sterling/dev/mynewt/defproj/repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/hal/nrf_power.h: In function 'nrf_power_rampower_mask_on':
/Users/sterling/dev/mynewt/defproj/repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/hal/nrf_power.h:981:25: error: implicit declaration of function 'ARRAY_SIZE' [-Werror=implicit-function-declaration]
     NRFX_ASSERT(block < ARRAY_SIZE(NRF_POWER->RAM));
                         ^
/Users/sterling/dev/mynewt/defproj/repos/apache-mynewt-core/libc/baselibc/include/assert.h:34:21: note: in definition of macro 'assert'
 #define assert(x) ((x) ? (void)0 : \
                     ^
/Users/sterling/dev/mynewt/defproj/repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/hal/nrf_power.h:981:5: note: in expansion of macro 'NRFX_ASSERT'
     NRFX_ASSERT(block < ARRAY_SIZE(NRF_POWER->RAM));
     ^
In file included from /Users/sterling/dev/mynewt/defproj/repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/nrfx.h:37:0,
                 from /Users/sterling/dev/mynewt/defproj/repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/drivers/src/nrfx_power_clock.c:32:
/Users/sterling/dev/mynewt/defproj/repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/drivers/include/nrfx_power_clock.h: In function 'nrfx_power_clock_irq_init':
/Users/sterling/dev/mynewt/defproj/repos/apache-mynewt-core/hw/mcu/nordic/include/nrfx_glue.h:87:42: error: implicit declaration of function 'NVIC_GetEnableIRQ' [-Werror=implicit-function-declaration]
 #define NRFX_IRQ_IS_ENABLED(irq_number) (NVIC_GetEnableIRQ(irq_number) == 1);
                                          ^
/Users/sterling/dev/mynewt/defproj/repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/drivers/include/nrfx_power_clock.h:59:10: note: in expansion of macro 'NRFX_IRQ_IS_ENABLED'
     if (!NRFX_IRQ_IS_ENABLED(POWER_CLOCK_IRQn))
          ^
/Users/sterling/dev/mynewt/defproj/repos/apache-mynewt-core/hw/mcu/nordic/include/nrfx_glue.h:87:77: error: expected ')' before ';' token
 #define NRFX_IRQ_IS_ENABLED(irq_number) (NVIC_GetEnableIRQ(irq_number) == 1);
                                                                             ^
/Users/sterling/dev/mynewt/defproj/repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/drivers/include/nrfx_power_clock.h:59:10: note: in expansion of macro 'NRFX_IRQ_IS_ENABLED'
     if (!NRFX_IRQ_IS_ENABLED(POWER_CLOCK_IRQn))
          ^
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/hw_mcu_nordic.dir/repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/drivers/src/nrfx_power_clock.c.obj] Error 1
make[1]: *** [CMakeFiles/hw_mcu_nordic.dir/all] Error 2
make: *** [all] Error 2

**Comment by andrzej-kaczmarek** [comment]
this is already fixed by #147
