### ISSUE TITLE
Relative path for cmake src and headers

### ISSUE THREAD

**Issue by mwilliford** [apache/mynewt-newt#160]
First, I love the target cmake ability, works with Clion, and changing targets is fast and easy now. 

However.... There is one small improvement which would make life better.  

The generated CMakeLists.txt has full path, and 'i think' this is what causes Clion to not recognize the files in the project tree, instead it lists them at the root level (flat).  When I search, it finds both full-path and relative path file for example.  

maybe some relative path option might help.  

This is a feature improvement request, not a bug.

**Comment by michal-narajowski** [comment]
Added in https://github.com/apache/mynewt-newt/pull/161 and merged.
