### ISSUE TITLE
Unable to have same named packages in two separate repos

### ISSUE THREAD

**Issue by sjanc** [apache/mynewt-newt#171]
newt build is not taking repository when checking for package name

eg we have two samples
apache-mynewt-nimble/apps/btshell
apache-mynewt-core/apps/btshell

and then target
```
[janc@ix mynewt]$ newt target show btshell
targets/btshell
    app=@apache-mynewt-core/apps/btshell
    bsp=@apache-mynewt-core/hw/bsp/nrf52840pdk
```

It is not possible to build this:
[janc@ix mynewt]$ newt build btshell
Building target targets/btshell
Error: Two app packages in build: apps/btshell, apps/btshell

I think newt should be able to distinguish packages with same name but from different repos. Especially now that we have nimble in separate repo (and more to come).

**Comment by sjanc** [comment]
new tarret show actually has is
```
[janc@ix mynewt]$ newt target show btshell
targets/btshell
    app=@apache-mynewt-core/apps/btshell
    bsp=@apache-mynewt-core/hw/bsp/nrf52840pdk
```

markup broke it as I didn't mark it as code:)

**Comment by ccollins476ad** [comment]
I am not able to replicate this.  Here is my target:
```
[ccollins@ccollins-mac:~/tmp/myproj3]$ newt target show btshell-nrf52dk
targets/btshell-nrf52dk
    app=@apache-mynewt-core/apps/btshell
    bsp=@apache-mynewt-core/hw/bsp/nrf52840pdk
    build_profile=debug
```

It builds successfully for me.  My `apache-mynewt-nimble` doesn't contain any apps, so I created an apps directory, copied `apps/btshell` there, and updated the `pkg.yml` with repo prefixes.

Is there a particular branch of the nimble repo that you are using to produce this error?

**Comment by sjanc** [comment]
OK, so for apps we cannot do that (since we can have only 1 app),  for lib like it could be useful to see full path in error message but this is not critical. Feel free to close it if you feel the change is not worth it.

**Comment by sdalu** [comment]
I guess I've just encountered the same kind of problem where using two repositories defining a compatibility layer for mynewt under the same package name:
~~~
 @repo1/port/mynewt
 @repo2/port/mynewt
~~~
This result in one of the port_mynewt.a being overwritten and failed linking
