### ISSUE TITLE
`newt test` exclude option does not accept fully-qualified package names

### ISSUE THREAD

**Issue by ccollins476ad** [apache/mynewt-newt#200]
`newt test` accepts an `--exclude` or `-e` switch.  The argument to this switch is a comma-separated list of packages to exclude from the test set.

The bug is that these package names must *not* include their repo name.  The tests are only properly excluded if the repo name is missing.

E.g.,

```
newt test all -e fs/fcb
```
properly excludes the `fs/fcb` test, but

```
newt test all -e @apache-mynewt-core/fs/fcb
```
excludes nothing; the fcb test still runs.

**Comment by michal-narajowski** [comment]
Fixed in https://github.com/apache/mynewt-newt/pull/208
