### ISSUE TITLE
Remove outdated information from README

### ISSUE THREAD

**Issue by artob** [apache/mynewt-newt#248]
The current [README](https://github.com/apache/mynewt-newt/blob/ac64d9297bc3ddb8ccf73aa89cc285a6943651d3/README.md) file contains manifestly out-of-date information, such as:

- _"We do not merge pull requests directly on Github, all PRs will be pulled and pushed through https://git.apache.org/."_ [No longer true, looking at the commit history.]
- _"Bugs can be filed on the [Apache Mynewt Bug Tracker](https://issues.apache.org/jira/browse/MYNEWT)._" [No longer true, there's nothing much in the JIRA instance, versus many issues here at GitHub.]
- _"Feature requests should also be filed on the [Apache Mynewt Bug Tracker](https://issues.apache.org/jira/browse/MYNEWT)."_ [As the previous.]

**Comment by ccollins476ad** [comment]
Thanks @artob.  I have submitted a PR to fix the issues you identified: https://github.com/apache/mynewt-newt/pull/332

Better late than never!
