### ISSUE TITLE
Unable to build a "split target"

### ISSUE THREAD

**Issue by flyingbepi** [apache/mynewt-newt#286]
Trying to build a split target setup following the Mynewt documentation,
I've configured the following targets:
Loader:
_targets/thingy-loader
    app=@apache-mynewt-core/apps/bleprph
    bsp=@apache-mynewt-core/hw/bsp/nordic_pca20020
    build_profile=optimized
    syscfg=BLE_LL_CFG_FEAT_LE_ENCRYPTION=0:BLE_SM_LEGACY=0_

Application:

 _targets/split-app
    app=@apache-mynewt-core/apps/splitty
    bsp=@apache-mynewt-core/hw/bsp/nordic_pca20020
    build_profile=optimized
    loader=@apache-mynewt-core/apps/bleprph
    syscfg=BLE_LL_CFG_FEAT_LE_ENCRYPTION=0:BLE_SM_LEGACY=0_

The loader target builds properly but I get the following error when building the application:

_**Error: Two app packages in build: apps/bleprph, apps/splitty**_

So, either a newt tool bug or an outdated documention ?

BTW,  I didn't find any explanation in the documentation to build a monolithic (One large image; upgrade not supported) application.

Thanks.

**Comment by ccollins476ad** [comment]
Hi @flyingbepi.  I am not able to replicate that exact problem, but I noticed that split image support is indeed broken.

This PR fixes the problem for me: https://github.com/apache/mynewt-newt/pull/293.  Would you mind giving it a try?

**Comment by flyingbepi** [comment]
Hi Chris,

Unfortunately, this PR didn't fix my issue since I got exactly the same error message.
Regards.
