### ISSUE TITLE
Error during execution of build.sh

### ISSUE THREAD

**Issue by KKopyscinski** [apache/mynewt-newt#390]
Running shell script causes error
```
./build.sh: 30: ./build.sh: go: not found
* Error: could not extract go version (version string: )
```
basically it cannot extract version number from `go version` command although this returns normal output, i.e.:
```
go version go1.14.1 linux/amd64
```

**Comment by sjanc** [comment]
I think we should invoke this as
#!/bin/sh -l
so that user login environment is used.

**Comment by ccollins476ad** [comment]
Thanks @KKopyscinski and @sjanc.  I have submitted this PR: https://github.com/apache/mynewt-newt/pull/405

**Comment by qiuchengkai** [comment]
怎么解决的？
