### ISSUE TITLE
Elliptic curves signed images can't be verified by mbedtls library

### ISSUE THREAD

**Issue by kasjer** [apache/mynewt-newt#450]
EC Signature when stored in TLV at the end of image can be padded with zeros.
I believe that it's done in create.go/GenerateSigEc().

mcuboot takes what is stored in TLV and passes it to mbedtls verification function that fails because it sees some extra bytes that do not belong to signature. (TinyCrypt version does not check this).

It seems that when TLV is created true signature size is lost.

**Comment by utzig** [comment]
Should be fixed by apache/mynewt-artifact#33 (after module dependency update here) and https://github.com/mcu-tools/mcuboot/pull/1188
