### ISSUE TITLE
DOCS: how to specify a device to flash when multiple are connected?

### ISSUE THREAD

**Issue by sacca97** [apache/mynewt-newt#560]
As per title, cannot find anything in the docs and JLink does not help

**Comment by sacca97** [comment]
Thanks to #239 

`--extrajtagcmd "-select usb=your board s/n"`

**Comment by andrzej-kaczmarek** [comment]
@sacca97 you can also use `JLINK_SN` env variable, i.e. `JLINK_SN=123456 newt load xxx` - this basically does the same  but it's easier to remember
